name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Ensure NPM 8
        run: npm install --global npm@8
      - name: Check if libraries are already deployed
        run: |
          VERSION=$(cat ".github/version.txt")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          IS_ON_NPM_OBSERVER=$(if [ ! -z "$(npm view svelte-rxjs-observer@$VERSION 2> /dev/null)" ]; then echo 'true'; else echo 'false'; fi)
          echo "IS_ON_NPM_OBSERVER=$IS_ON_NPM_OBSERVER" >> $GITHUB_ENV
          echo "$VERSION"
          echo "svelte-rxjs-observer is on npm: $IS_ON_NPM_OBSERVER"
      - name: Install dependencies
        run: npm install
      - name: Build all except apps
        run: |
          npm run build -- --exclude example
      - name: Release svelte-rxjs-observer on NPM
        if: env.IS_ON_NPM_OBSERVER != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish ./dist/libs/svelte-rxjs-observer --access public
      - name: Build Github Pages example
        run: |
          npm run build:example -- --baseHref '/${{ github.event.repository.name }}/'
      - name: Use index.html as 404.html
        run: |
          cp ./dist/apps/angular/index.html ./dist/apps/angular/404.html
      - name: Deploy Angular Example to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/angular
